[target.x86_64-linux-android.env]
passthrough = ["CFLAGS"]

[target.aarch64-linux-android.env]
passthrough = ["CFLAGS"]

[target.arm-linux-androideabi.env]
passthrough = ["CFLAGS"]

[target.aarch64-unknown-linux-gnu]
image = "rust:1.74.0-bookworm"
# Mergered all scripts/install_ubuntu_dependencies*.sh scripts
pre-build = [ """
dpkg --add-architecture arm64 && \
apt-get update && \
apt-get -y install \
  openssl \
  libssl-de:arm64 \
  pkg-config \
  libsqlite3-dev \
  git \
  cmake \
  dh-autoreconf \
  libc++-dev \
  libc++abi-dev \
  libprotobuf-dev \
  protobuf-compiler \
  libncurses5-dev \
  libncursesw5-dev \
  zip \
  curl \
  gcc-aarch64-linux-gnu \
  g++-aarch64-linux-gnu && \
rustup target add aarch64-unknown-linux-gnu && \
rustup target add wasm32-unknown-unknown && \
rustup toolchain install stable-aarch64-unknown-linux-gnu --force-non-host
""" ]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "CFLAGS",
  "RUST_DEBUG",
  "RUSTFLAGS",
  "ARCH",
  "FEATURES",
  "ROARING_ARCH",
  "TARGET",
  "RUST_TARGET",
  "BUILD_TARGET",
  "CARGO_BUILD_TARGET",
  "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc",
  "BINDGEN_EXTRA_CLANG_ARGS=--sysroot /usr/aarch64-linux-gnu/include/",
  "AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu/openssl/",
  "PKG_CONFIG_ALLOW_CROSS=1",
  "TARI_NETWORK",
]